# Generated by Django 4.2.27 on 2026-01-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_vision_api_key',
            field=models.TextField(blank=True, db_column='vision_api_key', default='', verbose_name='Vision API Key (加密)'),
        ),
    ]
