# Generated by Django 4.2.27 on 2025-12-30 06:27

import apps.images.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=apps.images.models.image_upload_path, verbose_name='图片文件')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'images',
                'ordering': ['-upload_time'],
            },
        ),
    ]
