# Generated by Django 4.2.27 on 2025-12-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exif_camera_make',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='相机品牌'),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_camera_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='相机型号'),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拍摄时间'),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_exposure_time',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='曝光时间'),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_f_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='光圈值'),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_focal_length',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='焦距'),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_gps_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS纬度'),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_gps_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS经度'),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_iso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ISO感光度'),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_parsed',
            field=models.BooleanField(default=False, verbose_name='EXIF已解析'),
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='图片')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '图片标签',
                'verbose_name_plural': '图片标签',
                'db_table': 'image_tags',
                'unique_together': {('image', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', through='images.ImageTag', to='tags.tag', verbose_name='标签'),
        ),
    ]
