# Generated by Django 4.2.27 on 2026-01-02 08:38

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_exif_camera_make_image_exif_camera_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processing_status',
            field=models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to=apps.images.models.thumbnail_upload_path, verbose_name='缩略图'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_generated',
            field=models.BooleanField(default=False, verbose_name='缩略图已生成'),
        ),
    ]
